apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b6qtw6cgs-python 
  janus-idp.io/tekton: b6qtw6cgs-python
  backstage.io/kubernetes-id: b6qtw6cgs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b6qtw6cgs-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml